name: CI
on:
  push:
  pull_request:
  schedule:
    - cron: "0 */13 * * *"
jobs:
  ci:
    name: CI
    strategy:
      matrix:
        go: ['1.18', '1.19', '1.20', '1.21']
        os: ['ubuntu-latest', 'windows-latest', 'macOS-latest']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - name: Run gofmt
        run: test -z "$(go fmt ./...)"
        shell: bash

      - name: Test pgregory.net/rand
        run: go test

      - name: Test practrand utility
        run: go test ./misc/practrand

      - name: Bench pgregory.net/rand
        run: go test -run=Benchmark -bench=.

      - name: Bench math/rand
        run: go test -tags=benchstd -run=Benchmark -bench=.

      - name: Bench golang.org/x/exp/rand
        run: go test -tags=benchx -run=Benchmark -bench=.
